### ISSUE TITLE
Add support for escripts

### ISSUE THREAD

**Issue by verbit** [sile/efmt#101]
This is a suggestion to support escript files as well by:
1. Considering files ending in `.escript` for formatting
2. Handling escript's shebang line correctly

Regarding 2., this is the error you get with `efmt`:
 ```console
$ rebar3 efmt -w myscript.escript
[2024-07-27T12:25:03Z ERROR efmt] Failed to format "myscript.escript"
    Parse failed:
    --> myscript.escript:1:2
    1 | #!/usr/bin/env escript
      |  ^ unexpected token
```

If I remove that line or comment it out (with `%`) then everything works fine.

**Comment by sile** [comment]
Sounds good. I will try to add escript support when I have time.
