### ISSUE TITLE
format of code with comments specified in ex_doc

### ISSUE THREAD

**Issue by 7run** [sile/efmt#109]
this is about the format when writing comments using the method specified by ex_doc, which is available from OTP27.

when the following code is formatted, it is expected to appear as shown in the link below

```erlang
-module(math).
-moduledoc """
A module for basic arithmetic.
""".

-export([add/2]).

-doc "Adds two numbers together.".
-spec add(number(), number()) -> number().
add(One, Two) ->
    One + Two.
```

> https://erlang.org/documentation/doc-15.0-rc1/doc/system/documentation.html

However, in reality, two blank lines are inserted between the function and the comment, as shown below:

```erlang
-module(math).
-moduledoc """
A module for basic arithmetic.
""".

-export([add/2]).

-doc "Adds two numbers together.".


-spec add(number(), number()) -> number().
add(One, Two) ->
    One + Two.
```

If there is any workaround, I would appreciate your advice.

**Comment by sile** [comment]
Thank you for reporting this issue. 
I think that `efmt` should be fixed to handle this case correctly.

**Comment by sile** [comment]
[FYI] Just released efmt-v0.18.3, which includes a fix for this issue.

**Comment by 7run** [comment]
Thank you very much.
I was able to use the corrected version successfully and the problem has been resolved.

**Comment by sile** [comment]
👍
