### ISSUE TITLE
How to with erlang.mk for this emft?

### ISSUE THREAD

**Issue by leeyisoft** [sile/efmt#41]

**Comment by sile** [comment]
I don't know what is "erlang.md". Maybe, did you mean [erlang.mk](https://erlang.mk/)?
Even if so, it's difficult to correctly answer your question as I'm not familiar with erlang.mk.
As a general answer, since `efmt` is a usual command-line tool, you could use that like other shell commands/programs after [installing the binary](https://github.com/sile/efmt#pre-built-binaries).

**Comment by leeyisoft** [comment]
> I don't know what is "erlang.md". Maybe, did you mean [erlang.mk](https://erlang.mk/)? Even if so, it's difficult to correctly answer your question as I'm not familiar with erlang.mk. As a general answer, since `efmt` is a usual command-line tool, you could use that like other shell commands/programs after [installing the binary](https://github.com/sile/efmt#pre-built-binaries).

Yes, I'm talking about Erlang. mk, which is implemented based on makefile syntax, emFT should integrate well into Erlang. mk, I would love to think emFT supports Erlang. mk, but I'm not familiar with Makefile syntax

是的，我说的是 erlang.mk, 它是基于makefile语法实现的，emft 应该很好集成到 erlang.mk，我很想 emft 支持 erlang.mk ，但是我不熟悉makefile语法

**Comment by sile** [comment]
I see. Thanks.
Unfortunately, I only know the name of `erlang.mk` and have never used it. So, I don't think that I can provide the integration well.

---

Looking at the top page of https://github.com/ninenines/erlang.mk, it seems an ordinally Makefile like the following:
```Makefile
PROJECT = webchat
DEPS = cowboy
dep_cowboy_commit = 2.8.0
include erlang.mk
```

You might be able to add lines to the Makefile as follows to support efmt:
```Makefile
PROJECT = webchat
DEPS = cowboy
dep_cowboy_commit = 2.8.0
include erlang.mk

# New make commands for efmt
format:
        # Format files.
        efmt -w

format-check:
        # Check whether the files are formatted and print diffs if those aren't.
        efmt -c
```

Now the following commands would work:
```console
$ make format
$ make format-check
```

I'm not sure this is the information you want, though.

**Comment by leeyisoft** [comment]
> I see. Thanks. Unfortunately, I only know the name of `erlang.mk` and have never used it. So, I don't think that I can provide the integration well.
> 
> Looking at the top page of https://github.com/ninenines/erlang.mk, it seems an ordinally Makefile like the following:
> 
> ```makefile
> PROJECT = webchat
> DEPS = cowboy
> dep_cowboy_commit = 2.8.0
> include erlang.mk
> ```
> 
> You might be able to add lines to the Makefile as follows to support efmt:
> 
> ```makefile
> PROJECT = webchat
> DEPS = cowboy
> dep_cowboy_commit = 2.8.0
> include erlang.mk
> 
> # New make commands for efmt
> format:
>         # Format files.
>         efmt -w
> 
> format-check:
>         # Check whether the files are formatted and print diffs if those aren't.
>         efmt -c
> ```
> 
> Now the following commands would work:
> 
> ```
> $ make format
> $ make format-check
> ```
> 
> I'm not sure this is the information you want, though.

Thank you very much, this is what I want; It would be nice to be able to "modify the source code directly after executing the command (rather than printing a modified copy)"

非常感谢，这是我想要的；如果能够“执行命令之后，直接把源代码修改好了（而不是输出一个修改好的副本）”那就更好了

**Comment by sile** [comment]
> this is what I want

👍 

>  "modify the source code directly after executing the command (rather than printing a modified copy)"

This is exactly what the `-w` (or `--write`) option does.

**Comment by leeyisoft** [comment]
> > 这就是我要的
> 
> 👍
> 
> > “执行命令后直接修改源代码（而不是打印修改后的副本）”
> 
> 这正是`-w`(or `--write`) 选项的作用。

Thanks again, I will try the interview in my personal project this evening, and then I will close the issue after it is done

**Comment by leeyisoft** [comment]
It's great, and works well with Erlang.mk


```
# New make commands for efmt
fmt:
	# Format files.
	./efmt --print-width 72 -w ./src/*.erl

```

**Comment by sile** [comment]
Congratulations 🎉
