### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by nkrylov** [sile/efmt#7]
https://github.com/sile/efmt/blob/master/rebar3_efmt/src/rebar3_efmt_command.erl#L59 this line causes compilation error

**Comment by sile** [comment]
Thank you for reporting this issue.
As L59 uses [the "Numeric literals with underscore" feature](https://www.erlang.org/blog/otp-23-highlights/#numeric-literals-with-underscore) introduced by OTP-23, Erlang/OTP releases older than that will raise a compilation error.
However, there is no strong reason to use the relatively new feature in the file. I'm going to fix the file soon.

**Comment by nkrylov** [comment]
@sile didn't know they exist, thanks for the link!

**Comment by sile** [comment]
Fixed and published v0.1.1. Thanks!
