### ISSUE TITLE
Add support for colored diff

### ISSUE THREAD

**Issue by verbit** [sile/efmt#91]
I think it would be nice if `efmt` could support a colored diff (similar to Python black's `--color` option [1]). While it is possible to workaround the missing colors with `colordiff`, that feels like a hack, especially since `efmt` outputs some messages before the actual diff.

[1] https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#color-no-color

**Comment by sile** [comment]
Sounds good. I'll try adding color diff support within a ween.
