### ISSUE TITLE
`efmt` lists non-existing files

### ISSUE THREAD

**Issue by verbit** [sile/efmt#97]
When working with a git repo, `efmt` produces incorrect file listings. Here is a minimal example:
```console
$ mkdir test && cd test
$ echo "-module(efmt_test)." > efmt_test.erl
$ git init
$ git add efmt_test.erl
$ git commit -m "initial commit"
$ mkdir src
$ mv efmt_test.erl src/efmt_test.erl
$ efmt --show-files
efmt_test.erl
src/efmt_test.erl
$ efmt -w
[2024-07-14T18:54:43Z INFO  efmt] The following files were added as the default input files:
    - efmt_test.erl
    - src/efmt_test.erl
[2024-07-14T18:54:43Z ERROR efmt] Failed to format "efmt_test.erl"
    No such file or directory (os error 2)

Error: Failed to format the following files:
- efmt_test.erl
$ echo $?
1
$ efmt -V
efmt 0.16.0
```

Note how `efmt` lists the old location of the files and tries to format it, resulting in an error. Instead, `efmt` should succeed (not even a warning).

I think the issue is how `efmt` is listing files in a git repo here https://github.com/sile/efmt/blob/acac8da5e733af5a5de3b566fbfecc5dfd6c61cc/src/files.rs#L92

`git ls-files` indeed shows the old location of the file in the above example. Why is this used at all? Is it for the `.gitignore` handling? I guess one quick way to fix the issue would be to compute the intersection between "file listing with git" and "file listing without git" and use that as the final file listing. Though, it feels a bit hacky.

**Comment by sile** [comment]
Yes, `git ls-files` is used for `.gitignore` handling.
However, the current behavior you've pointed out is a bug that needs to be fixed.
I'm not sure but crates for `.gitignore` handling (e.g., https://github.com/BurntSushi/ripgrep/tree/master/crates/ignore) might be used for this purpose instead of calling `git` command.

**Comment by sile** [comment]
I will attempt the above approach to address this issue (maybe) this weekend. Or, if you are interested in contributing to fixing this issue, it would be welcomed.

**Comment by verbit** [comment]
Making myself comfortable with Rust is still on my to-do list. Right now, it would take me too long to fix it, I'm afraid. So go ahead, if you can :slightly_smiling_face:.

**Comment by sile** [comment]
No problem. Thank you for your response 👍
